version: "3.7"

services:
  nano-work-server:
    build: .
    image: nano-work-server
    command: -c 3 -l 0.0.0.0:7000

  nginx:
    image: nginx
    ports:
      - 7000:7000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
